version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  workspace:
    build:
      context: ./containers/workspace
    volumes:
      - ./server:/home/eqemu/server:delegated
      - ./code:/home/eqemu/code:delegated
      - ./scripts:/home/eqemu/scripts:delegated
    ports:
      - 2222/tcp:22/tcp
      - 2222/udp:22/udp
      - 9000/tcp:9000/tcp
      - 9000/udp:9000/udp
      - 5999/tcp:5999/tcp
      - 5999/udp:5999/udp
      - 5998/tcp:5998/tcp
      - 5998/udp:5998/udp
      - 7000-7100/tcp:7000-7100/tcp
      - 7000-7100/tcp:7000-7100/udp
    command: >
      bash -c "./scripts/create-symlinks.pl; /bin/bash"
    tty: true
    networks:
      - backend
  mariadb:
    build: ./containers/mariadb
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - backend